config/routes.rb
Appsample::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships,    :only => [:create, :destroy]
  
  root :to => 'pages#home'
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://ctrlv.us/">MLV Group</a>
    by Lance Velasco
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path  %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://google.com/">Google</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <% end %>          
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
          <li><%= link_to "Sign out", signout_path %></li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<scriptsrc="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>

        <%= stylesheet_link_tag "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= render 'layouts/shim' %>    
	    </head>
		<body>
		<%= render 'layouts/header' %>
		<div class="container">
		    <% flash.each do |key, value| %>
                   <%= content_tag(:div, value, class: "alert alert-#{key}") %>
                 <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>  
		</body>  
	</html>